<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit301ac16403f2b6bfc7e114ab0baaa05c
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Dwoo\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Dwoo\\' => 
        array (
            0 => __DIR__ . '/..' . '/dwoo/dwoo/lib/Dwoo',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit301ac16403f2b6bfc7e114ab0baaa05c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit301ac16403f2b6bfc7e114ab0baaa05c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
